# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 01:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.EmailField(max_length=80)),
                ('password', models.CharField(max_length=80)),
                ('user_token', models.CharField(max_length=80)),
                ('consumer_key', models.CharField(max_length=120)),
                ('consumer_secret', models.CharField(max_length=120)),
                ('request_token_url', models.CharField(default='https://login.salesforce.com/services/oauth2/token', max_length=255)),
                ('access_token_url', models.CharField(default='https://login.salesforce.com/services/oauth2/token', max_length=255)),
                ('http_proxy', models.CharField(default='http://PITC-Zscaler-US-MilwaukeeZ.proxy.corporate.ge.com:9400', max_length=255, null=True)),
                ('https_proxy', models.CharField(default='https://PITC-Zscaler-US-MilwaukeeZ.proxy.corporate.ge.com:9400', max_length=255, null=True)),
                ('object_refresh_date', models.DateTimeField(editable=False, null=True, verbose_name='objects refreshed')),
            ],
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maxed.Credential')),
            ],
        ),
        migrations.CreateModel(
            name='DataSetField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DataSetFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('=', 'Equals'), ('!=', 'Not equal'), ('<', 'Less Than'), ('<=', 'Less than or equal'), ('>=', 'Greater than or equal'), ('>', 'Greater than'), ('StartsWith', 'Starts With'), ('Contains', 'Contains'), ('EndsWith', 'Ends With')], max_length=10)),
                ('value', models.CharField(max_length=255)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maxed.DataSetField')),
            ],
        ),
        migrations.CreateModel(
            name='DataSetObj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rel_pos', models.IntegerField(default=0, editable=False)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maxed.DataSet')),
            ],
        ),
        migrations.CreateModel(
            name='FieldRef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FilterGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('AND', 'AND'), ('OR', 'OR')], max_length=10)),
                ('datasetobj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maxed.DataSetObj')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='maxed.FilterGroup')),
            ],
        ),
        migrations.CreateModel(
            name='ForceField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregatable', models.BooleanField(default=False)),
                ('autoNumber', models.BooleanField(default=False)),
                ('byteLength', models.IntegerField(blank=True, null=True)),
                ('calculated', models.BooleanField(default=False)),
                ('calculatedFormula', models.CharField(blank=True, max_length=255, null=True)),
                ('cascadeDelete', models.BooleanField(default=False)),
                ('caseSensitive', models.BooleanField(default=False)),
                ('controllerName', models.CharField(blank=True, max_length=40, null=True)),
                ('createable', models.BooleanField(default=False)),
                ('custom', models.BooleanField(default=False)),
                ('defaultValue', models.CharField(blank=True, max_length=40, null=True)),
                ('defaultValueFormula', models.CharField(blank=True, max_length=40, null=True)),
                ('defaultedOnCreate', models.BooleanField(default=False)),
                ('dependentPicklist', models.BooleanField(default=False)),
                ('deprecatedAndHidden', models.BooleanField(default=False)),
                ('digits', models.IntegerField(blank=True, null=True)),
                ('displayLocationInDecimal', models.BooleanField(default=False)),
                ('encrypted', models.BooleanField(default=False)),
                ('externalId', models.BooleanField(default=False)),
                ('extraTypeInfo', models.CharField(blank=True, max_length=40, null=True)),
                ('filterable', models.BooleanField(default=False)),
                ('filteredLookupInfo', models.CharField(blank=True, max_length=40, null=True)),
                ('groupable', models.BooleanField(default=False)),
                ('highScaleNumber', models.BooleanField(default=False)),
                ('htmlFormatted', models.BooleanField(default=False)),
                ('idLookup', models.BooleanField(default=False)),
                ('inlineHelpText', models.CharField(blank=True, max_length=255, null=True)),
                ('label', models.CharField(max_length=40)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('mask', models.CharField(blank=True, max_length=40, null=True)),
                ('maskType', models.CharField(blank=True, max_length=40, null=True)),
                ('name', models.CharField(max_length=40)),
                ('nameField', models.BooleanField(default=False)),
                ('namePointing', models.BooleanField(default=False)),
                ('nillable', models.BooleanField(default=False)),
                ('permissionable', models.BooleanField(default=False)),
                ('precision', models.IntegerField(blank=True, null=True)),
                ('queryByDistance', models.BooleanField(default=False)),
                ('referenceTargetField', models.CharField(blank=True, max_length=40, null=True)),
                ('relationshipName', models.CharField(blank=True, max_length=40, null=True)),
                ('relationshipOrder', models.CharField(blank=True, max_length=40, null=True)),
                ('restrictedDelete', models.BooleanField(default=False)),
                ('restrictedPicklist', models.BooleanField(default=False)),
                ('scale', models.IntegerField(blank=True, null=True)),
                ('soapType', models.CharField(max_length=40)),
                ('sortable', models.BooleanField(default=False)),
                ('fftype', models.CharField(max_length=40)),
                ('unique', models.BooleanField(default=False)),
                ('updateable', models.BooleanField(default=False)),
                ('writeRequiresMasterRead', models.BooleanField(default=False)),
                ('commonly_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ForceObj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('label', models.CharField(max_length=80)),
                ('activateable', models.BooleanField(default=False)),
                ('createable', models.BooleanField(default=False)),
                ('custom', models.BooleanField(default=False)),
                ('customSetting', models.BooleanField(default=False)),
                ('deletable', models.BooleanField(default=False)),
                ('deprecatedAndHidden', models.BooleanField(default=False)),
                ('feedEnabled', models.BooleanField(default=False)),
                ('keyPrefix', models.CharField(blank=True, max_length=20, null=True)),
                ('labelPlural', models.CharField(blank=True, max_length=80, null=True)),
                ('layoutable', models.BooleanField(default=False)),
                ('mergeable', models.BooleanField(default=False)),
                ('mruEnabled', models.BooleanField(default=False)),
                ('queryable', models.BooleanField(default=False)),
                ('replicateable', models.BooleanField(default=False)),
                ('retrieveable', models.BooleanField(default=False)),
                ('searchable', models.BooleanField(default=False)),
                ('triggerable', models.BooleanField(default=False)),
                ('undeletable', models.BooleanField(default=False)),
                ('updateable', models.BooleanField(default=False)),
                ('commonly_used', models.BooleanField(default=False)),
                ('description_refresh_date', models.DateTimeField(editable=False, null=True, verbose_name='description refreshed')),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maxed.Credential')),
            ],
        ),
        migrations.CreateModel(
            name='Picklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('defaultValue', models.BooleanField(default=False)),
                ('label', models.CharField(max_length=40)),
                ('validFor', models.CharField(blank=True, max_length=40, null=True)),
                ('value', models.CharField(max_length=40)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maxed.ForceField')),
            ],
        ),
        migrations.AddField(
            model_name='forcefield',
            name='forceobj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maxed.ForceObj'),
        ),
        migrations.AddField(
            model_name='fieldref',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maxed.ForceField'),
        ),
        migrations.AddField(
            model_name='fieldref',
            name='forceobj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maxed.ForceObj'),
        ),
        migrations.AddField(
            model_name='datasetobj',
            name='forceobj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maxed.ForceObj'),
        ),
        migrations.AddField(
            model_name='datasetfilter',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maxed.FilterGroup'),
        ),
        migrations.AddField(
            model_name='datasetfield',
            name='datasetobj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maxed.DataSetObj'),
        ),
        migrations.AddField(
            model_name='datasetfield',
            name='forcefield',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maxed.ForceField'),
        ),
    ]
