# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='http_proxy',
            field=models.CharField(blank=True, default='http://PITC-Zscaler-US-MilwaukeeZ.proxy.corporate.ge.com:9400', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='credential',
            name='https_proxy',
            field=models.CharField(blank=True, default='https://PITC-Zscaler-US-MilwaukeeZ.proxy.corporate.ge.com:9400', max_length=255, null=True),
        ),
    ]
