# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxed', '0002_auto_20161015_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='http_proxy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='credential',
            name='https_proxy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
