# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maxed', '0003_auto_20161017_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetfield',
            name='hidden',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='datasetfilter',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maxed.FilterGroup'),
        ),
        migrations.AlterField(
            model_name='filtergroup',
            name='operator',
            field=models.CharField(choices=[('AND', 'AND'), ('OR', 'OR')], default='AND', max_length=10),
        ),
    ]
