# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxed', '0004_auto_20161017_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picklist',
            name='label',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
