# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxed', '0005_auto_20161017_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetobj',
            name='in_use',
            field=models.BooleanField(default=False),
        ),
    ]
