# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maxed', '0006_datasetobj_in_use'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filtergroup',
            name='datasetobj',
        ),
        migrations.AddField(
            model_name='filtergroup',
            name='dataset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='maxed.DataSet'),
            preserve_default=False,
        ),
    ]
