# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maxed', '0007_auto_20161017_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filtergroup',
            name='dataset',
        ),
        migrations.AddField(
            model_name='filtergroup',
            name='datasetobj',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='maxed.DataSetObj'),
            preserve_default=False,
        ),
    ]
